version: 0.2

phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - ng build --prod
    post_build:
         commands:
            - printenv
            - aws s3 sync --delete dist/CDDemo s3://arn:aws:s3:::project-2-bucket-bwalker
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist/*'
    discard-paths: yes
